/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBlinkenPanel.java
 *
 * Created on 09/01/2013, 20:24:31
 */
package name.guillaumes.jordi.jblinkenserver;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jguillaumes
 */
public class JBlinkenPanel extends javax.swing.JFrame {
    private static final String hexdig="0123456789ABCDEF";
    
    
    private JLabel makeBitLabel(String text) {
        JLabel lbl = new JLabel();
        lbl.setText(text);
        lbl.setPreferredSize(new Dimension(30,10));        
        lbl.setMinimumSize(new Dimension(30,10));    
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setFont(lbl.getFont().deriveFont(lbl.getFont().getSize()-3f));

        return lbl;
    }
    
    /** Creates new form JBlinkenPanel */
    public JBlinkenPanel() {

        initComponents();
        
        iconRed     = new ImageIcon(getClass().getResource("/resources/Red.png"));
        iconGreen   = new ImageIcon(getClass().getResource("/resources/Green.png"));
        iconOrange  = new ImageIcon(getClass().getResource("/resources/Orange.png"));
        iconBlack   = new ImageIcon(getClass().getResource("/resources/Black.png"));

        // ((FlowLayout) ledPanel.getLayout()).setHgap(5);
        
        errorLabel.setIcon(iconBlack);
        parityLabel.setIcon(iconBlack);
        
        ledPanel.add(errorLabel);
        labelPanel.add(makeBitLabel("E"));
        ledPanel.add(parityLabel);
        labelPanel.add(makeBitLabel("P"));
        
        JPanel sepPanel = new JPanel();
        sepPanel.setMinimumSize(new Dimension(15,40));
        JPanel sepPanell = new JPanel();
        sepPanell.setMinimumSize(new Dimension(15,40));
        ledPanel.add(sepPanel);
        labelPanel.add(sepPanell);
        
        for(int i=15; i>=0; i--) {
            bitsLabel[i] = new JLabel();
            bitsLabel[i].setIcon(iconBlack);
            ledPanel.add(bitsLabel[i]);
            labelPanel.add(makeBitLabel(hexdig.substring(i, i+1)));
        }
        
        statusPanel.setPreferredSize(statusPanel.getMinimumSize());
        pack();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        ledPanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        statusPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        recvdLabel = new javax.swing.JLabel();
        fillPanel = new javax.swing.JPanel();
        oofLabel = new javax.swing.JLabel();
        nboundLabel = new javax.swing.JLabel();
        tmoutLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nskipLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        udpPortFTF = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        startBT = new javax.swing.JButton();
        stopBT = new javax.swing.JButton();
        zeroBT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDP11 Blinkenlights (DATA only)");
        setMinimumSize(new java.awt.Dimension(700, 200));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        topPanel.setLayout(new java.awt.BorderLayout());

        ledPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ledPanel.setMinimumSize(new java.awt.Dimension(660, 40));
        ledPanel.setPreferredSize(new java.awt.Dimension(660, 40));
        topPanel.add(ledPanel, java.awt.BorderLayout.NORTH);

        labelPanel.setMinimumSize(new java.awt.Dimension(660, 15));
        labelPanel.setPreferredSize(new java.awt.Dimension(660, 15));
        topPanel.add(labelPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        statusPanel.setMaximumSize(null);
        statusPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel2, gridBagConstraints);

        statusLabel.setText("Idle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 80.0;
        statusPanel.add(statusLabel, gridBagConstraints);

        jLabel3.setText("Received frames:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Out-of-order frames:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Non-bound source frames:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Timeouts:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel6, gridBagConstraints);

        recvdLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 30.0;
        statusPanel.add(recvdLabel, gridBagConstraints);

        fillPanel.setMinimumSize(new java.awt.Dimension(200, 10));
        fillPanel.setPreferredSize(new java.awt.Dimension(10, 200));
        fillPanel.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 50.0;
        statusPanel.add(fillPanel, gridBagConstraints);

        oofLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 30.0;
        statusPanel.add(oofLabel, gridBagConstraints);

        nboundLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 30.0;
        statusPanel.add(nboundLabel, gridBagConstraints);

        tmoutLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 30.0;
        statusPanel.add(tmoutLabel, gridBagConstraints);

        jLabel7.setText("Skipped frames:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        statusPanel.add(jLabel7, gridBagConstraints);

        nskipLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        statusPanel.add(nskipLabel, gridBagConstraints);

        getContentPane().add(statusPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("UDP port");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1);

        udpPortFTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        udpPortFTF.setText("11696");
        jPanel3.add(udpPortFTF);

        bottomPanel.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));

        startBT.setText("Start");
        startBT.setName("startBT"); // NOI18N
        jPanel2.add(startBT);

        stopBT.setText("Stop");
        stopBT.setName("stopBT"); // NOI18N
        jPanel2.add(stopBT);

        zeroBT.setText("Zero");
        jPanel2.add(zeroBT);

        bottomPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

        this.setVisible(false);         this.dispose();     }//GEN-LAST:event_exitMenuItemActionPerformed

        
    ImageIcon iconRed;
    ImageIcon iconGreen;   
    ImageIcon iconOrange;
    ImageIcon iconBlack;
    JLabel[]  bitsLabel   = new JLabel[16];
    JLabel    parityLabel = new JLabel();
    JLabel    errorLabel  = new JLabel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel bottomPanel;
    javax.swing.JMenuItem exitMenuItem;
    javax.swing.JMenu fileMenu;
    javax.swing.JPanel fillPanel;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel labelPanel;
    javax.swing.JPanel ledPanel;
    javax.swing.JLabel nboundLabel;
    javax.swing.JLabel nskipLabel;
    javax.swing.JLabel oofLabel;
    javax.swing.JLabel recvdLabel;
    javax.swing.JButton startBT;
    javax.swing.JLabel statusLabel;
    javax.swing.JPanel statusPanel;
    javax.swing.JButton stopBT;
    javax.swing.JLabel tmoutLabel;
    javax.swing.JPanel topPanel;
    javax.swing.JFormattedTextField udpPortFTF;
    javax.swing.JButton zeroBT;
    // End of variables declaration//GEN-END:variables
}
