/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBlinkenPanel.java
 *
 * Created on 09/01/2013, 20:24:31
 */
package name.guillaumes.jordi.jblinkenserver;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author jguillaumes
 */
public class JBlinkenPanel extends javax.swing.JFrame {

    
    
    /** Creates new form JBlinkenPanel */
    public JBlinkenPanel() {
        int x = 100;
        int y = 50;

        initComponents();
        
        iconRed     = new ImageIcon(getClass().getResource("/resources/Red.png"));
        iconGreen   = new ImageIcon(getClass().getResource("/resources/Green.png"));
        iconOrange  = new ImageIcon(getClass().getResource("/resources/Orange.png"));
        iconBlack   = new ImageIcon(getClass().getResource("/resources/Black.png"));
        
        for (int i=15; i>=0; i--) {
            bitsLabel[i] = new JLabel();
            bitsLabel[i].setIcon(iconBlack);
            getContentPane().add(bitsLabel[i], new AbsoluteConstraints(x, y));
            x += 35;
        }
        
        errorLabel.setIcon(iconBlack);
        parityLabel.setIcon(iconBlack);
        
        getContentPane().add(errorLabel, new AbsoluteConstraints(20,y));
        getContentPane().add(parityLabel, new AbsoluteConstraints(55,y));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        udpPortFTF = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        startBT = new javax.swing.JButton();
        stopBT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("UDP port");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        udpPortFTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        udpPortFTF.setText("11696");
        udpPortFTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udpPortFTFActionPerformed(evt);
            }
        });
        jPanel3.add(udpPortFTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 30));

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));

        startBT.setText("Start");
        startBT.setName("startBT"); // NOI18N
        startBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTActionPerformed(evt);
            }
        });
        jPanel2.add(startBT);

        stopBT.setText("Stop");
        stopBT.setName("stopBT"); // NOI18N
        jPanel2.add(stopBT);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 370, 40));

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

        this.setVisible(false);         this.dispose();     }//GEN-LAST:event_exitMenuItemActionPerformed

    private void startBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startBTActionPerformed

    private void udpPortFTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udpPortFTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udpPortFTFActionPerformed

        
    ImageIcon iconRed;
    ImageIcon iconGreen;   
    ImageIcon iconOrange;
    ImageIcon iconBlack;
    JLabel[]  bitsLabel   = new JLabel[16];
    JLabel    parityLabel = new JLabel();
    JLabel    errorLabel  = new JLabel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem exitMenuItem;
    javax.swing.JMenu fileMenu;
    javax.swing.JLabel jLabel1;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JButton startBT;
    javax.swing.JButton stopBT;
    javax.swing.JFormattedTextField udpPortFTF;
    // End of variables declaration//GEN-END:variables
}
