DEBUG=/NODEBUG
LDEBUG=$(DEBUG)
OPTIMIZE=/OPTIMIZE
BFLAGS=$(BFLAGS)$(DEBUG)$(OPTIMIZE)/LIST/MACHINE=(ASSEMB,SYM,NOBIN,UNIQ)/CROSS/DESIGN
LINKFLAGS=$(LINKFLAGS)/MAP/FULL$(LDEBUG)

ALL :	FIXTIM.EXE
	@ WRITE SYS$OUTPUT "*** DONE ***"

FIXTIM.OBJ :	FIXTIM.BLI CHARMACROS.BLI
